### ISSUE TITLE
Unable to compile on MacOS (arm64)

### ISSUE THREAD

**Issue by taynaron** [UltraStar-Deluxe/UltraStar-Creator#29]
Compiling with Qt 6.5 on an M2 mac with macos 14.0 is failing with the below. Can USC include dylibs for arm64?
```
ld: warning: ignoring file 'ultrastar_creator/lib/macx/libcld2.dylib': found architecture 'x86_64', required architecture 'arm64'
ld: Undefined symbols:
  CLD2::LanguageDeclaredName(CLD2::Language), referenced from:
      QUMainWindow::on_pushButton_BrowseSubtitles_clicked() in QUMainWindow.o
      QUMainWindow::determineLanguage(QString) in QUMainWindow.o
  CLD2::DetectLanguageSummary(char const*, int, bool, CLD2::Language*, int*, int*, bool*), referenced from:
      QUMainWindow::on_pushButton_BrowseSubtitles_clicked() in QUMainWindow.o
      QUMainWindow::determineLanguage(QString) in QUMainWindow.o
```

**Comment by bohning** [comment]
Could you try to compile cld2 for arm64 yourself? See https://github.com/UltraStar-Deluxe/UltraStar-Creator/issues/18. If you succeed to compile the arm64 dylibs, I will happily include them in the repository.

**Comment by taynaron** [comment]
I have successfully compiled an arm64 libcld2.dylib, and changed a couple of bits in the qmake.pro. I have successfully compiled the app, but now the app fails to launch. The dump is below. Any thoughts/ideas? The intel version provided for download fails to launch in a similar manner.

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               UltraStar-Creator [59515]
Path:                  /Users/USER/*/UltraStar-Creator.app/Contents/MacOS/UltraStar-Creator
Identifier:            com.yourcompany.UltraStar-Creator
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-11-19 19:00:07.7669 -0800
OS Version:            macOS 14.0 (23A344)
Report Version:        12
Anonymous UUID:        B262DDEF-B83E-3280-BEFE-C86AF1E0EE2B

Sleep/Wake UUID:       77BD2CAB-0854-4A93-8A1C-5DD9C40B37E7

Time Awake Since Boot: 1200000 seconds
Time Since Wake:       2847 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))
Exception Codes:       UNKNOWN_0x32 at 0x0000000103290000
Exception Codes:       0x0000000000000032, 0x0000000103290000

Termination Reason:    Namespace CODESIGNING, Code 2 Invalid Page

VM Region Info: 0x103290000 is in 0x103290000-0x103370000;  bytes after start: 0  bytes before end: 917503
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      mapped file                 103288000-103290000    [   32K] r--/rwx SM=COW  ...t_id=c57ee3ef
--->  mapped file                 103290000-103370000    [  896K] r--/rwx SM=COW  ...t_id=c618abef
      GAP OF 0xf0000 BYTES
      mapped file                 103460000-103604000    [ 1680K] r-x/rwx SM=COW  ...t_id=c3f9c5ef

Thread 0 Crashed:
0   dyld                          	       0x1833dcb00 dyld3::MachOFile::hasMachOMagic() const + 0
1   dyld                          	       0x1833b019c dyld4::SyscallDelegate::mapFileReadOnly(Diagnostics&, char const*, unsigned long*, dyld4::FileID*, bool*, char*) const + 228
2   dyld                          	       0x1833afb00 dyld4::SyscallDelegate::withReadOnlyMappedFile(Diagnostics&, char const*, bool, void (void const*, unsigned long, bool, dyld4::FileID const&, char const*) block_pointer) const + 88
3   dyld                          	       0x1833a8ba4 dyld4::JustInTimeLoader::makeJustInTimeLoaderDisk(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, bool, unsigned int, mach_o::Layout const*) + 208
4   dyld                          	       0x18339dc74 dyld4::Loader::makeDiskLoader(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, bool, unsigned int, mach_o::Layout const*) + 172
5   dyld                          	       0x18339f230 invocation function for block in dyld4::Loader::getLoader(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&) + 2056
6   dyld                          	       0x18339e340 dyld4::Loader::forEachResolvedAtPathVar(dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, dyld4::ProcessConfig::PathOverrides::Type, bool&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer) + 776
7   dyld                          	       0x18338bb20 dyld4::ProcessConfig::PathOverrides::forEachPathVariant(char const*, dyld3::Platform, bool, bool, bool&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer) const + 556
8   dyld                          	       0x18339de78 dyld4::Loader::forEachPath(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer) + 248
9   dyld                          	       0x18339e6a8 dyld4::Loader::getLoader(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&) + 808
10  dyld                          	       0x1833a6ad0 invocation function for block in dyld4::JustInTimeLoader::loadDependents(Diagnostics&, dyld4::RuntimeState&, dyld4::Loader::LoadOptions const&) + 412
11  dyld                          	       0x1833dd2c8 invocation function for block in dyld3::MachOFile::forEachDependentDylib(void (char const*, bool, bool, bool, unsigned int, unsigned int, bool&) block_pointer) const + 148
12  dyld                          	       0x1833852fc dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const + 300
13  dyld                          	       0x1833dd0fc dyld3::MachOFile::forEachDependentDylib(void (char const*, bool, bool, bool, unsigned int, unsigned int, bool&) block_pointer) const + 172
14  dyld                          	       0x1833a6814 dyld4::JustInTimeLoader::loadDependents(Diagnostics&, dyld4::RuntimeState&, dyld4::Loader::LoadOptions const&) + 164
15  dyld                          	       0x183389754 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 1176
16  dyld                          	       0x183388f44 start + 1948


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000103290000   x1: 0x0000000000000000   x2: 0x000000016d281b58   x3: 0x0000000000040002
    x4: 0x0000000000000003   x5: 0x0000000000000000   x6: 0x000000016d281b58   x7: 0x0000000000000b80
    x8: 0x000000016d2819f0   x9: 0x000000016d2819f8  x10: 0x0000000001000014  x11: 0x0000000000000001
   x12: 0x000000016d2821f2  x13: 0x0000000000000000  x14: 0x000000023af0c87a  x15: 0x0000000000008000
   x16: 0x000000000000005c  x17: 0x0000000183386f90  x18: 0x0000000000000000  x19: 0x000000016d2820e0
   x20: 0x0000000000000003  x21: 0x000000016d281b2f  x22: 0x0000000103290000  x23: 0x000000016d281b58
   x24: 0x000000016d281b30  x25: 0x000000016d281b50  x26: 0x000000016d281ff0  x27: 0x000000010311ee30
   x28: 0x0000000000000000   fp: 0x000000016d281b10   lr: 0x00000001833b019c
    sp: 0x000000016d2819f0   pc: 0x00000001833dcb00 cpsr: 0x80001000
   far: 0x0000000103290000  esr: 0x92000007 (Data Abort) byte read Translation fault

Binary Images:
       0x102b7c000 -        0x102cdffff com.yourcompany.UltraStar-Creator (*) <a076a384-c62d-38cb-800f-8e97bc953e4d> /Users/USER/*/UltraStar-Creator.app/Contents/MacOS/UltraStar-Creator
       0x183383000 -        0x183416873 dyld (*) <ffd8ab66-c9ab-31df-ab80-3a3dff367ddd> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=888.6M resident=0K(0%) swapped_out_or_unallocated=888.6M(100%)
Writable regions: Total=12.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=12.3M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE (reserved)              64K        1         reserved VM address space (unallocated)
__DATA                              27K        2 
__DATA_CONST                        38K        2 
__DATA_DIRTY                         7K        1 
__LINKEDIT                       886.6M        2 
__TEXT                            2016K        2 
dyld private memory               4384K        4 
mapped file                       3152K       10 
===========                     =======  ======= 
TOTAL                            960.1M       26 
TOTAL, minus reserved VM space   960.0M       26 



-----------
Full Report
-----------

{"app_name":"UltraStar-Creator","timestamp":"2023-11-19 19:00:07.00 -0800","app_version":"","slice_uuid":"a076a384-c62d-38cb-800f-8e97bc953e4d","build_version":"","platform":1,"bundleID":"com.yourcompany.UltraStar-Creator","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.0 (23A344)","roots_installed":0,"name":"UltraStar-Creator","incident_id":"B98691C8-5612-4EF4-AB85-9EBCB0099C21"}
{
  "uptime" : 1200000,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac14,7",
  "coalitionID" : 191371,
  "osVersion" : {
    "train" : "macOS 14.0",
    "build" : "23A344",
    "releaseType" : "User"
  },
  "captureTime" : "2023-11-19 19:00:07.7669 -0800",
  "codeSigningMonitor" : 1,
  "incident" : "B98691C8-5612-4EF4-AB85-9EBCB0099C21",
  "pid" : 59515,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-11-19 19:00:07.7411 -0800",
  "procStartAbsTime" : 30751252305602,
  "procExitAbsTime" : 30751252737919,
  "procName" : "UltraStar-Creator",
  "procPath" : "\/Users\/USER\/*\/UltraStar-Creator.app\/Contents\/MacOS\/UltraStar-Creator",
  "bundleInfo" : {"CFBundleIdentifier":"com.yourcompany.UltraStar-Creator"},
  "storeInfo" : {"deviceIdentifierForVendor":"9BB51A1A-7087-5D42-A6C5-BC94A8E65133","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.yourcompany.UltraStar-Creator",
  "crashReporterKey" : "B262DDEF-B83E-3280-BEFE-C86AF1E0EE2B",
  "codeSigningID" : "UltraStar-Creator",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 587334144,
  "codeSigningValidationCategory" : 0,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"SwEJi2sJQLl\/AQhroAAAVClBAJE\/gQPxQf\/\/VMADX9ZAaWn4wANf1g==","atPC":"CABAuemsn1LJ7q9yPwVIa+AXnxrAA1\/WwANf1ggAQLnprJ9Sye6vcg=="},
  "wakeTime" : 2847,
  "sleepWakeUUID" : "77BD2CAB-0854-4A93-8A1C-5DD9C40B37E7",
  "sip" : "enabled",
  "vmRegionInfo" : "0x103290000 is in 0x103290000-0x103370000;  bytes after start: 0  bytes before end: 917503\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      mapped file                 103288000-103290000    [   32K] r--\/rwx SM=COW  ...t_id=c57ee3ef\n--->  mapped file                 103290000-103370000    [  896K] r--\/rwx SM=COW  ...t_id=c618abef\n      GAP OF 0xf0000 BYTES\n      mapped file                 103460000-103604000    [ 1680K] r-x\/rwx SM=COW  ...t_id=c3f9c5ef",
  "exception" : {"codes":"0x0000000000000032, 0x0000000103290000","rawCodes":[50,4347985920],"type":"EXC_BAD_ACCESS","signal":"SIGKILL (Code Signature Invalid)","subtype":"UNKNOWN_0x32 at 0x0000000103290000"},
  "termination" : {"flags":0,"code":2,"namespace":"CODESIGNING","indicator":"Invalid Page"},
  "vmregioninfo" : "0x103290000 is in 0x103290000-0x103370000;  bytes after start: 0  bytes before end: 917503\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      mapped file                 103288000-103290000    [   32K] r--\/rwx SM=COW  ...t_id=c57ee3ef\n--->  mapped file                 103290000-103370000    [  896K] r--\/rwx SM=COW  ...t_id=c618abef\n      GAP OF 0xf0000 BYTES\n      mapped file                 103460000-103604000    [ 1680K] r-x\/rwx SM=COW  ...t_id=c3f9c5ef",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":16505659,"threadState":{"x":[{"value":4347985920},{"value":0},{"value":6126312280},{"value":262146},{"value":3},{"value":0},{"value":6126312280},{"value":2944},{"value":6126311920},{"value":6126311928},{"value":16777236},{"value":1},{"value":6126313970},{"value":0},{"value":9578793082},{"value":32768},{"value":92},{"value":6496481168,"symbolLocation":56,"symbol":"fcntl"},{"value":0},{"value":6126313696},{"value":3},{"value":6126312239},{"value":4347985920},{"value":6126312280},{"value":6126312240},{"value":6126312272},{"value":6126313456},{"value":4346474032},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6496649628},"cpsr":{"value":2147487744},"fp":{"value":6126312208},"sp":{"value":6126311920},"esr":{"value":2449473543,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":6496832256,"matchesCrashFrame":1},"far":{"value":4347985920}},"frames":[{"imageOffset":367360,"symbol":"dyld3::MachOFile::hasMachOMagic() const","symbolLocation":0,"imageIndex":1},{"imageOffset":184732,"symbol":"dyld4::SyscallDelegate::mapFileReadOnly(Diagnostics&, char const*, unsigned long*, dyld4::FileID*, bool*, char*) const","symbolLocation":228,"imageIndex":1},{"imageOffset":183040,"symbol":"dyld4::SyscallDelegate::withReadOnlyMappedFile(Diagnostics&, char const*, bool, void (void const*, unsigned long, bool, dyld4::FileID const&, char const*) block_pointer) const","symbolLocation":88,"imageIndex":1},{"imageOffset":154532,"symbol":"dyld4::JustInTimeLoader::makeJustInTimeLoaderDisk(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, bool, unsigned int, mach_o::Layout const*)","symbolLocation":208,"imageIndex":1},{"imageOffset":109684,"symbol":"dyld4::Loader::makeDiskLoader(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, bool, unsigned int, mach_o::Layout const*)","symbolLocation":172,"imageIndex":1},{"imageOffset":115248,"symbol":"invocation function for block in dyld4::Loader::getLoader(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&)","symbolLocation":2056,"imageIndex":1},{"imageOffset":111424,"symbol":"dyld4::Loader::forEachResolvedAtPathVar(dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, dyld4::ProcessConfig::PathOverrides::Type, bool&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer)","symbolLocation":776,"imageIndex":1},{"imageOffset":35616,"symbol":"dyld4::ProcessConfig::PathOverrides::forEachPathVariant(char const*, dyld3::Platform, bool, bool, bool&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer) const","symbolLocation":556,"imageIndex":1},{"imageOffset":110200,"symbol":"dyld4::Loader::forEachPath(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer)","symbolLocation":248,"imageIndex":1},{"imageOffset":112296,"symbol":"dyld4::Loader::getLoader(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&)","symbolLocation":808,"imageIndex":1},{"imageOffset":146128,"symbol":"invocation function for block in dyld4::JustInTimeLoader::loadDependents(Diagnostics&, dyld4::RuntimeState&, dyld4::Loader::LoadOptions const&)","symbolLocation":412,"imageIndex":1},{"imageOffset":369352,"symbol":"invocation function for block in dyld3::MachOFile::forEachDependentDylib(void (char const*, bool, bool, bool, unsigned int, unsigned int, bool&) block_pointer) const","symbolLocation":148,"imageIndex":1},{"imageOffset":8956,"symbol":"dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const","symbolLocation":300,"imageIndex":1},{"imageOffset":368892,"symbol":"dyld3::MachOFile::forEachDependentDylib(void (char const*, bool, bool, bool, unsigned int, unsigned int, bool&) block_pointer) const","symbolLocation":172,"imageIndex":1},{"imageOffset":145428,"symbol":"dyld4::JustInTimeLoader::loadDependents(Diagnostics&, dyld4::RuntimeState&, dyld4::Loader::LoadOptions const&)","symbolLocation":164,"imageIndex":1},{"imageOffset":26452,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":1176,"imageIndex":1},{"imageOffset":24388,"symbol":"start","symbolLocation":1948,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4340563968,
    "CFBundleIdentifier" : "com.yourcompany.UltraStar-Creator",
    "size" : 1458176,
    "uuid" : "a076a384-c62d-38cb-800f-8e97bc953e4d",
    "path" : "\/Users\/USER\/*\/UltraStar-Creator.app\/Contents\/MacOS\/UltraStar-Creator",
    "name" : "UltraStar-Creator"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6496464896,
    "size" : 604276,
    "uuid" : "ffd8ab66-c9ab-31df-ab80-3a3dff367ddd",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 6495715328,
  "size" : 4012523520,
  "uuid" : "7906534c-5d2b-3ba8-b9c6-93a5cf1b7b50"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=888.6M resident=0K(0%) swapped_out_or_unallocated=888.6M(100%)\nWritable regions: Total=12.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=12.3M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE (reserved)              64K        1         reserved VM address space (unallocated)\n__DATA                              27K        2 \n__DATA_CONST                        38K        2 \n__DATA_DIRTY                         7K        1 \n__LINKEDIT                       886.6M        2 \n__TEXT                            2016K        2 \ndyld private memory               4384K        4 \nmapped file                       3152K       10 \n===========                     =======  ======= \nTOTAL                            960.1M       26 \nTOTAL, minus reserved VM space   960.0M       26 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "f26a56f9a2658d00fc6ce9cfe5d58f8c421426a5",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "639124e81d92412bfb4880b3",
      "factorPackIds" : {

      },
      "deploymentId" : 240000012
    },
    {
      "rolloutId" : "6112d17137f5d11121dcd4e2",
      "factorPackIds" : {

      },
      "deploymentId" : 240000450
    }
  ],
  "experiments" : [

  ]
}
}

Model: Mac14,7, BootROM 10151.1.1, proc 8:4:4 processors, 24 GB, SMC 
Graphics: Apple M2, Apple M2, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4378), wl0: Jul  8 2023 18:16:54 version 18.20.438.0.7.8.162 FWID 01-1b580da0
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
```

**Comment by bohning** [comment]
```EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))``` sounds like the code needs to be signed for 14.0?

**Comment by taynaron** [comment]
Looks like it's an apple silicon "security" feature:

https://github.com/dotnet/maui/issues/12483
https://developer.apple.com/forums/thread/698870

**Comment by taynaron** [comment]
I'm at a loss. I've recompiled all the dylibs, codesigned each using codesign --force -s - </path/to/dylib> (per [this stackoverflow](https://apple.stackexchange.com/questions/343912/should-i-sign-open-source-code-myself)), compiled, then codesigned the newly created app with the same codesign, and am still getting the sigkill. Any ideas?

**Comment by taynaron** [comment]
I've written a branch with all my compile changes for macOS. It's not ready to merge because the program still crashes on codesigning, and the changes I made will break intel mac compilation.
https://github.com/taynaron/UltraStar-Creator/tree/mac_arm_compile

**Comment by DeinAlptraum** [comment]
Sorry for the late reply. If you're still around, you could test one of the MAC-ARM build artifacts from the build I'm currently testing: https://github.com/UltraStar-Deluxe/UltraStar-Creator/actions/runs/9568475176
I don't have a Mac, so cannot test any of this myself unfortunately

**Comment by taynaron** [comment]
I get the following error: “UltraStar-Creator” is damaged and can’t be opened. You should move it to the Trash.

I expect this is a codesigning issue too. I'm happy to help diagnose as you work through this.

**Comment by DeinAlptraum** [comment]
Thank you, that would be much appreciated!
Just noticed I made a mistake on the codesigning command, which I fixed in [this build](https://github.com/UltraStar-Deluxe/UltraStar-Creator/actions/runs/9598539028). Would be nice if you could test this!

I'm not exactly familiar with how the codesigning works, but I tried  `codesign --force --deep --sign - UltraStar-Creator.dmg` which was enough to get the ARM build for USDX to run, so I'm hoping that'll work here as well

**Comment by taynaron** [comment]
Still failing with that new build. Same issue. I found some logs that may be useful (replaced pids with 'x')

AUTHREQ_ATTRIBUTION: msgID=508.93, attribution={accessing={TCCDProcess: identifier=UltraStar-Creator, pid=x, auid=501, euid=501, binary_path=/Applications/Audio/UltraStar-Creator.app/Contents/MacOS/UltraStar-Creator}, requesting={TCCDProcess: identifier=com.apple.syspolicyd, pid=x, auid=0, euid=0, binary_path=/usr/libexec/syspolicyd}, },
AUTHREQ_SUBJECT: msgID=508.93, subject=com.yourcompany.UltraStar-Creator,

[app<application.com.yourcompany.UltraStar-Creator.32080320.32080477(501)>:92888] termination reported by launchd (9, 8, 9)

ASP: Security policy would not allow process: 92888, /Applications/Audio/UltraStar-Creator.app/Contents/MacOS/UltraStar-Creator

**Comment by DeinAlptraum** [comment]
Okay so apparently the previous codesign attempts didn't even sign anything at all because you can't sign `.dmg`s, but the command doesn't tell you that... great.
Anyway, [next attempt](https://github.com/UltraStar-Deluxe/UltraStar-Creator/actions/runs/9601216951)
@taynaron I am once again asking for your support

**Comment by taynaron** [comment]
Ah yes, I should have mentioned that something was up with the DMG; glad you got that.

Progress! The app now fails to launch with "UltraStar-Creator can't be opened because Apple cannot check it for malicious software." Knowledgeable folks can open the app despite this, and so I have! Ideally you can figure out what's triggering that warning, as it's quite intimidating for most folks.

**Comment by DeinAlptraum** [comment]
Okay, so you were able to start the app now? (with "workarounds")

Unfortunately I don't think we can really get any further than that, since that would require proper notarization with a developer's licencese that's a hundred bucks a year afaik

**Comment by taynaron** [comment]
ah right, I'm used to a different error for this. Great! I'll poke at the program itself in the next few days, see if the functionality works on macOS. Thanks for the work in getting it running!

**Comment by DeinAlptraum** [comment]
Thank you for helping with testing!

Regarding the signing/notarization, I'm happy to be corrected, but (as someone who doesn't use any Apple devices) this is what I've gathered.

I will close the issue after the changes for this are merged. If you notice any problems, feel free to reopen/open a new issue.

**Comment by lfp2** [comment]
Hello, I'm trying to run the new version, but I am receiving the following error 

"make: *** No rule to make target `../lib/macx/libcld2.dylib', needed by `../bin/release/UltraStar-Creator.app/Contents/Frameworks/libcld2.dylib'.  Stop."

**Comment by DeinAlptraum** [comment]
@lfp2 can you describe what you were trying to do exactly? This looks like you were trying to compile it, not run the image.
If all you want to do is run the software, you can find an up-to-date image for ARM (M1/M2) Macs [here](https://github.com/UltraStar-Deluxe/UltraStar-Creator/actions/runs/9613128893) (download the 
MAC-x86-UltraStar-Creator-image)

If you want to compile this yourself: unfortunately I haven't gotten around to update the build instructions yet, so for now the Github workflow _is_ the build instructions, which you can find [here](https://github.com/UltraStar-Deluxe/UltraStar-Creator/blob/45ccd4b67294ff21f1122fe7ff9a7dd2f091dfb7/.github/workflows/main.yml#L88).
From your error specifically, it looks like you haven't compiled cld2. The steps to do so are as follows:
1. Ensure you've cloned the repository with submodules, i.e. that the `include/cld2` folder is not empty.
2. Execute these commands to prepare the cld2 build script, compile and place the lib in the linking directory 
```
cd include/cld2/internal/
export CFLAGS="-Wno-narrowing -O3"
sed -i '' "s/soname=/install_name,/g" compile_libs.sh
sed -i '' "s/-shared/-dynamiclib/g" compile_libs.sh
sed -i '' "s/libcld2.so/libcld2.dylib/g" compile_libs.sh
sed -i '' "s/libcld2_full.so/libcld2_full.dylib/g" compile_libs.sh
./compile_libs.sh
cp libcld2.dylib ../../../lib/macx
```
3. Try building again as you did before
